CREATE TABLE `cheques` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cliente_id` int NOT NULL,
	`numero_cheque` varchar(50),
	`banco` varchar(100),
	`agencia` varchar(20),
	`conta` varchar(30),
	`emitente` varchar(255) NOT NULL,
	`cpf_cnpj_emitente` varchar(20),
	`valor_nominal` decimal(15,2) NOT NULL,
	`data_vencimento` date NOT NULL,
	`taxa_desconto` decimal(8,4) NOT NULL,
	`tipo_taxa` enum('mensal','diaria','anual') NOT NULL DEFAULT 'mensal',
	`valor_desconto` decimal(15,2) NOT NULL,
	`valor_liquido` decimal(15,2) NOT NULL,
	`status` enum('aguardando','compensado','devolvido','cancelado') NOT NULL DEFAULT 'aguardando',
	`conta_caixa_id` int,
	`data_compensacao` timestamp,
	`motivo_devolucao` varchar(255),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cheques_id` PRIMARY KEY(`id`)
);
